# REF: https://starship.rs/config/

format = '$all'

# Inserts blank line between shell prompts (true)
add_newline = false

# Timeout to scan files (in ms, 30)
scan_timeout = 30

# Timeout for executed commands (in ms, 500)
command_timeout = 500

[shell]
disabled = false
